### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by LonePaladin** [ChristofferDahlen/Pathfinder-Cheatsheet#3]
* Page 1
 * Social Activities
     * **Coerce:** CS: Target won 't retaliate soon. (Remove space in "won 't")
 * Traveling Activities
     * **Hustle:** Double your travel speed of 10 x Con miniatures. (Should read "for 10 × Con minutes")
     * **Squeeze:** a space you can barley fit through. (It's "barely")
     * **Scout:** bonus to INITATIVE (It's "INITIATIVE", you missed an I in the middle)
* Page 2
 * **Disable Device:** THEIVES' TOOLS (Should be "THIEVES' TOOLS")
 * **Pick Lock:** Same as above
* Page 3
 * **Dying Condition:** Loose if HP > 0. (Should be "Lose")
 * **Wounded Condition:**  if you are att full HP (Should be "at full HP")
 * **Petrified:** You become a object (Should be "an object")
* Page 4
 * **Start of Turn:** gain/loose extra actions (It's "lose")
* Page 6
 * **Grimoire Trait:** prepared with Grimore . (Misspelled "Grimoire")
 * **Wand Trait:** Wand is destoryed. (It's "destroyed")
* All over
 * **Spacing:** Multiple instances of inconsistent spacing, usually around punctuation (like sentences ending in a space before the period), parenthesis, and abbreviations.

**Comment by ChristofferDahlen** [comment]
Thanks guys!

The builtin spellchecker I have isn't the best. It has some problems...

My code auto formatting has caused certain problems with the spacing when I moved over from command to environment.

The spelling fixes are now done. Going through the spacing now.

**Comment by ChristofferDahlen** [comment]
Most of this should be fixed. If you have some extra time it would be great if you could do another read through.
